CI: validate deploy manifest for missing files

diff --git a/.github/workflows/ci_tests_run_notebooks.yml b/.github/workflows/ci_tests_run_notebooks.yml
--- a/.github/workflows/ci_tests_run_notebooks.yml
+++ b/.github/workflows/ci_tests_run_notebooks.yml
@@ -47,6 +47,9 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
 
+      - name: Validating manifest
+        run: bash -c 'missing=false; for file in $(cat deploy_to_fornax_manifest.in); do if [ ! -f $file ]; then echo "Inconsistent" $file; missing=true; fi; done; if $missing; then exit 1; fi'
+
       - name: Install dependencies
         run: python -m pip install --upgrade tox
 
